"""empty message

Revision ID: 323517fc9c6f
Revises: 19c679b33717
Create Date: 2020-01-06 00:43:03.846287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323517fc9c6f'
down_revision = '19c679b33717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
