"""empty message

Revision ID: 598e2b6b19fd
Revises: 451688430428
Create Date: 2020-01-07 13:55:02.405804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598e2b6b19fd'
down_revision = '451688430428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('interviewed', sa.String(length=5), nullable=True))
    op.create_index(op.f('ix_application_interviewed'), 'application', ['interviewed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_interviewed'), table_name='application')
    op.drop_column('application', 'interviewed')
    # ### end Alembic commands ###
