"""empty message

Revision ID: bd37c0f51222
Revises: cc1906a31f02
Create Date: 2020-01-06 11:19:39.357095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd37c0f51222'
down_revision = 'cc1906a31f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('status', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'status')
    # ### end Alembic commands ###
