"""empty message

Revision ID: cc1906a31f02
Revises: 0cdbcf3836e6
Create Date: 2020-01-06 11:09:56.736434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1906a31f02'
down_revision = '0cdbcf3836e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('company', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'company')
    # ### end Alembic commands ###
